### ISSUE TITLE
vio

### ISSUE THREAD

**Issue by ArthurHoumo** [hku-mars/FAST-LIVO2#22]
你好，能否不接LiDAR，以vio方式运行呢？或者用一个深度估计模型代替LiDAR输入，达到vio或稠密重建的目的呢

**Comment by xuankuzcr** [comment]
必须有可以提供深度的传感器，livo2里面的vio才能跑起来。因为系统里没有一个用来三角化产生3d点的后端。
但可以用深度相机或者其他能提供深度的模块替代LiDAR输入。
