### ISSUE TITLE
What's the camera lens specific model, please?

### ISSUE THREAD

**Issue by ResearcherYan** [hku-mars/FAST-LIVO2#34]
Thanks for your team's great work, Mr. Zheng. The paper shows you use hikrobot camera MV-CA013-21UC. Could you please tell us the camera lens specific model as well? Cause I'm a new drone system builder and have no idea what the ideal `working distance` and `target width/height` for a drone should be. Thanks a lot!

**Comment by xuankuzcr** [comment]
Thank you for your attention! You can refer to lens models like MVL-HF0628M-6MPE and LM5JCM.

**Comment by ResearcherYan** [comment]
Okay, I got it. Thanks for your precious advice! PS: Sorry for the late reply.
