### ISSUE TITLE
关于法向优化的问题

### ISSUE THREAD

**Issue by Roger-Chuh** [hku-mars/FAST-LIVO2#41]
郑博您好，看了您的paper很受启发，正在尝试复现相关trick。论文实验部分有提到normal refinement时用的patch size是11x11，有几个问题想请问下，
1. 如果size降到8x8，效果降幅大吗，
2. 以及一般情况下需要与reference patch有多少帧共视才能把normal估计得比较好，
3. 再有就是优化时对normal初值精度的要求高吗，我是做纯vio的，没法通过lidar points获取初值，只能通过其他手段获取。
期待您的回复，感谢。

**Comment by xuankuzcr** [comment]
1. 11x11是能接受的最小的patch size了，再小收敛速度会很慢
2. 这与reference patch的梯度分布有关
3. 在仿真中（见下图），初值可以偏差20°，但在实际应用中不好说
![simulation](https://github.com/user-attachments/assets/97a842cf-8992-4bdb-81ec-fb8d9ae9e545)

**Comment by Roger-Chuh** [comment]
感谢大佬的回复，解决了心中的疑惑。
