### ISSUE TITLE
Harware for the Project

### ISSUE THREAD

**Issue by Gaaaavin** [hku-mars/FAST-LIVO2#8]
What kind of hardware is required for thie project?
Is it similar to that for Fast-LIVO?
Is hardware synchronization between camera and lidar required?

**Comment by xuankuzcr** [comment]
Thank you for your interest in our work. 
1. You will need a set of LiDAR, IMU, and camera. These sensors can be of any model as this is a universal solution
2. The hardware requirements are similar to those of FAST-LIVO. However, our project supports a wider range of LiDAR and camera models, covering all common types available in the market.
3. Please refer to this issue #7.

**Comment by Gaaaavin** [comment]
Thank you!
