### ISSUE TITLE
像mid360这种雷达，可以不接相机吗？就用雷达和imu数据能跑不？

### ISSUE THREAD

**Issue by ZOUJIASHUAI** [hku-mars/FAST-LIVO2#9]

**Comment by xuankuzcr** [comment]
可以的。如果只提供LiDAR数据，系统会运行纯LO（LiDAR Odometry）模式。如果提供LiDAR和IMU数据，系统会运行LIO（LiDAR-Inertial Odometry）模式。如果同时提供LiDAR、IMU和camera数据，系统则会运行LIVO（LiDAR-Inertial-Visual Odometry）模式。系统会根据输入数据自动选择相应的模式运行。

**Comment by ZOUJIASHUAI** [comment]
niubi
